// AUTO-GENERATED STUB — replace with real output from: yarn compile
// This stub allows the frontend to build before the Compact compiler runs.

/**
 * Reads ledger state from raw on-chain data bytes.
 * @param {Uint8Array} data - Raw ledger data from indexer
 * @returns {object} Decoded ledger state
 */
export function ledger(data) {
  // Stub implementation — real implementation generated by compact compile
  throw new Error(
    'VeilVault: ledger() stub called. Run "yarn compile" to generate real contract artifacts.',
  );
}

/**
 * Pure circuits — deterministic functions for key derivation and nullifier creation
 */
export const pureCircuits = {
  vault_admin_key: (sk) => {
    throw new Error('VeilVault: vault_admin_key() stub. Run yarn compile.');
  },
  make_voter_nullifier: (id) => {
    throw new Error('VeilVault: make_voter_nullifier() stub. Run yarn compile.');
  },
};

/**
 * Contract class stub
 */
export class Contract {
  constructor() {
    throw new Error('VeilVault: Contract stub. Run yarn compile.');
  }
}
